//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNFe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Certificado {
            get {
                return ((string)(this["Certificado"]));
            }
            set {
                this["Certificado"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/cadconsultacadastro4.asmx")]
        public string ServiceNFe_Homologacao_ConsultaCadastroContribuinte4_CadConsultaCadastro4 {
            get {
                return ((string)(this["ServiceNFe_Homologacao_ConsultaCadastroContribuinte4_CadConsultaCadastro4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/cadconsultacadastro4.asmx")]
        public string ServiceNFe_ConsultaCadastroContribuinte4_CadConsultaCadastro4 {
            get {
                return ((string)(this["ServiceNFe_ConsultaCadastroContribuinte4_CadConsultaCadastro4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx")]
        public string ServiceNFe_Inutilizacao4_NFeInutilizacao4 {
            get {
                return ((string)(this["ServiceNFe_Inutilizacao4_NFeInutilizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx")]
        public string ServiceNFe_Homologacao_Inutilizacao4_NFeInutilizacao4 {
            get {
                return ((string)(this["ServiceNFe_Homologacao_Inutilizacao4_NFeInutilizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx")]
        public string ServiceNFe_Homologacao_NFeStatusServico4_NFeStatusServico4 {
            get {
                return ((string)(this["ServiceNFe_Homologacao_NFeStatusServico4_NFeStatusServico4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx")]
        public string ServiceNFe_NFeStatusServico4_NFeStatusServico4 {
            get {
                return ((string)(this["ServiceNFe_NFeStatusServico4_NFeStatusServico4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx")]
        public string ServiceNFe_NFeConsultaProtocolo4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["ServiceNFe_NFeConsultaProtocolo4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx")]
        public string ServiceNFe_Homologacao_NFeConsultaProtocolo4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["ServiceNFe_Homologacao_NFeConsultaProtocolo4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx")]
        public string ServiceNFe_Homologacao_RecepcaoEvento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["ServiceNFe_Homologacao_RecepcaoEvento4_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx")]
        public string ServiceNFe_RecepcaoEvento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["ServiceNFe_RecepcaoEvento4_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx")]
        public string ServiceNFe_Homologacao_NFeAutorizacao4_NFeAutorizacao4 {
            get {
                return ((string)(this["ServiceNFe_Homologacao_NFeAutorizacao4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx")]
        public string ServiceNFe_NFeAutorizacao4_NFeAutorizacao4 {
            get {
                return ((string)(this["ServiceNFe_NFeAutorizacao4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx")]
        public string ServiceNFe_NFeRetAutorizacao4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["ServiceNFe_NFeRetAutorizacao4_NFeRetAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx")]
        public string ServiceNFe_Homologacao_NFeRetAutorizacao4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["ServiceNFe_Homologacao_NFeRetAutorizacao4_NFeRetAutorizacao4"]));
            }
        }
    }
}
